#!/usr/bin/env python3
# bot/constants/config.py
'''
loaded by utils.py, console.py, and bot.py

not really sure why this file is called "config" but eh
if it aint broke dont fix it

spark says:
NOTE: these constants here aren't exactly user configurable aside from prompt
      which leads me to think that i should move prompt to the .env file
      and have it be loaded by another constant file (because circular imports cant have it here)

NOTE: nvm the above NOTE is stupid
      in a now reverted merge commit,
      i attempted to do this exact thing, but uh
      circular imports still happen.
      why, you may ask? because utils.get_env_var() depends on console.log()
      and console.log() depends on prompt
      and prompt is generated by a utils.get_env_var() call.
      im sure you see where i'm going with this.
'''

# LIBRARIES AND MODULES

from pathlib import Path

# CONSTANTS

env_path = Path(".env")

default_prefix = "."

prompt = "% "

units = {
  "d": 86400, # days
  "h": 3600,  # hours
  "m": 60,    # minutes
  "s": 1      # seconds
}